spring:
  profiles:
    active: dev
#person:
#  lastName: lisi
#  age: 18
#  boss: false
#  maps: {k1: v1, k2: v2}
#  lists:
#    - list
#    - zhaoliu
#  dog:
#    name: xiaogou
#    age: 2
#  birth: 2017/12/12
#  email: 13636@163.com
---
server:
  port: 8083
  servlet:
    context-path: /kyle
name:
  test1: "lisi8083 \n lisi"
  test2: 'lisi8083 \n lisi'
spring:
  profiles: dev
---
server:
  port: 8084
name:
  test1: "lisi8084 \n lisi"
  test2: 'lisi8084 \n lisi'
  spring:
    profiles: prod